package com.mikemilla.wordnerd.words;

import com.mikemilla.wordnerd.Syllables;

import java.util.ArrayList;

public class Pro implements Syllables {

    public static ArrayList<String> singles = new ArrayList<String>();
    public static ArrayList<String> doubles = new ArrayList<String>();
    public static ArrayList<String> triples = new ArrayList<String>();
    public static ArrayList<String> quadruples = new ArrayList<String>();
    public static ArrayList<String> quintuples = new ArrayList<String>();
    public static ArrayList<String> sextuples = new ArrayList<String>();

    public Pro() {
        singles.add("AU");
        singles.add("AUX");
        singles.add("BEAU");
        singles.add("BEAUX");
        singles.add("BLEAU");
        singles.add("BLOW");
        singles.add("BO");
        singles.add("BOEH");
        singles.add("BOWE");
        singles.add("BREAU");
        singles.add("BREAULT");
        singles.add("BREAUX");
        singles.add("BRO");
        singles.add("BROE");
        singles.add("BROWE");
        singles.add("CHAU");
        singles.add("CHO");
        singles.add("CHOE");
        singles.add("CLOE");
        singles.add("CLOW");
        singles.add("CO");
        singles.add("CROW");
        singles.add("DAU");
        singles.add("DOE");
        singles.add("DOH");
        singles.add("DOUGH");
        singles.add("EAU");
        singles.add("EAUX");
        singles.add("FLOE");
        singles.add("FLOW");
        singles.add("FOE");
        singles.add("FRO");
        singles.add("FROH");
        singles.add("GAU");
        singles.add("GLOE");
        singles.add("GLOW");
        singles.add("GO");
        singles.add("GROW");
        singles.add("HO");
        singles.add("JOE");
        singles.add("KNOW");
        singles.add("KROGH");
        singles.add("KROH");
        singles.add("KROWE");
        singles.add("LOW");
        singles.add("MAU");
        singles.add("MEAUX");
        singles.add("MOE");
        singles.add("MOW");
        singles.add("NAU");
        singles.add("NEAULT");
        singles.add("NO");
        singles.add("OH");
        singles.add("OWE");
        singles.add("PLOUGH");
        singles.add("PO");
        singles.add("QUEAU");
        singles.add("QUO");
        singles.add("REAUX");
        singles.add("RHEAULT");
        singles.add("RHO");
        singles.add("ROE");
        singles.add("ROW");
        singles.add("SCHAU");
        singles.add("SCHMO");
        singles.add("SEW");
        singles.add("SGRO");
        singles.add("SHOW");
        singles.add("SLOE");
        singles.add("SLOW");
        singles.add("SNOW");
        singles.add("SO");
        singles.add("STOW");
        singles.add("STROH");
        singles.add("STROW");
        singles.add("THOUGH");
        singles.add("THROE");
        singles.add("THROW");
        singles.add("TOE");
        singles.add("TOW");
        singles.add("TROW");
        singles.add("TSO");
        singles.add("WOE");
        singles.add("WROE");
        singles.add("YAU");
        singles.add("YO");
        singles.add("ZOH");
        
        doubles.add("AGLO");
        doubles.add("AGLOW");
        doubles.add("AGO");
        doubles.add("ALTHOUGH");
        doubles.add("ARNAUD");
        doubles.add("ARNAULT");
        doubles.add("BADEAU");
        doubles.add("BADEAUX");
        doubles.add("BARBEAU");
        doubles.add("BEAUDREAU");
        doubles.add("BEBEAU");
        doubles.add("BEGNAUD");
        doubles.add("BELLEAU");
        doubles.add("BELOW");
        doubles.add("BESTOW");
        doubles.add("BIBEAU");
        doubles.add("BIBEAULT");
        doubles.add("BIO");
        doubles.add("BISCOE");
        doubles.add("BLINCOE");
        doubles.add("BOILEAU");
        doubles.add("BOISSEAU");
        doubles.add("BONNEAU");
        doubles.add("BORDEAU");
        doubles.add("BORDEAUX");
        doubles.add("BOUDREAU");
        doubles.add("BOUDREAUX");
        doubles.add("BOURBEAU");
        doubles.add("BOURDEAU");
        doubles.add("BOURGAULT");
        doubles.add("BRANCHEAU");
        doubles.add("BRASSEAUX");
        doubles.add("BRAZEAU");
        doubles.add("BRIDEAU");
        doubles.add("BROSSEAU");
        doubles.add("BROUSSEAU");
        doubles.add("BRUNEAU");
        doubles.add("BRUSSEAU");
        doubles.add("BUDREAU");
        doubles.add("BUTEAU");
        doubles.add("CABO");
        doubles.add("CAMPEAU");
        doubles.add("CHABOT");
        doubles.add("CHAMPEAU");
        doubles.add("CHANGSHO");
        doubles.add("CHATEAU");
        doubles.add("CHATEAUX");
        doubles.add("CHENAULT");
        doubles.add("COINTREAU");
        doubles.add("COMEAU");
        doubles.add("COMEAUX");
        doubles.add("COMPEAU");
        doubles.add("COUSTEAU");
        doubles.add("CREPEAU");
        doubles.add("CROTEAU");
        doubles.add("CROTTEAU");
        doubles.add("DAIGNAULT");
        doubles.add("DAIGNEAULT");
        doubles.add("DAVAO");
        doubles.add("DAVAULT");
        doubles.add("DEBOE");
        doubles.add("DEDEAUX");
        doubles.add("DEFOE");
        doubles.add("DENAULT");
        doubles.add("DENEAU");
        doubles.add("DENEAULT");
        doubles.add("DEVAULT");
        doubles.add("DEVAUX");
        doubles.add("DEVEAU");
        doubles.add("DEVEAUX");
        doubles.add("DEVOE");
        doubles.add("DRAPEAU");
        doubles.add("DUBEAU");
        doubles.add("DUFAULT");
        doubles.add("DUNNO");
        doubles.add("DUSSAULT");
        doubles.add("DUSSEAU");
        doubles.add("DUSSEAULT");
        doubles.add("ENLOE");
        doubles.add("ENLOW");
        doubles.add("ENSLOW");
        doubles.add("ESCOE");
        doubles.add("ESCROW");
        doubles.add("FACTEAU");
        doubles.add("FAUCHEUX");
        doubles.add("FAUROT");
        doubles.add("FAUTEUX");
        doubles.add("FAVREAU");
        doubles.add("FECTEAU");
        doubles.add("FOREGO");
        doubles.add("FORGO");
        doubles.add("FREGEAU");
        doubles.add("FURLAUD");
        doubles.add("GARCEAU");
        doubles.add("GAREAU");
        doubles.add("GARNEAU");
        doubles.add("GATEAU");
        doubles.add("GAUDREAU");
        doubles.add("GAUTHREAUX");
        doubles.add("GAUTREAU");
        doubles.add("GAUTREAUX");
        doubles.add("GAUVREAU");
        doubles.add("GENDREAU");
        doubles.add("GEORGIOU");
        doubles.add("GIBEAU");
        doubles.add("GIBEAULT");
        doubles.add("GIRAUD");
        doubles.add("GODOT");
        doubles.add("GOUDEAU");
        doubles.add("GOUDREAU");
        doubles.add("GROLEAU");
        doubles.add("GUANDJO");
        doubles.add("GUILBAULT");
        doubles.add("GUILBEAU");
        doubles.add("GUILBEAULT");
        doubles.add("GUILBEAUX");
        doubles.add("GUILLOT");
        doubles.add("HELLO");
        doubles.add("HOHO");
        doubles.add("HURTEAU");
        doubles.add("INCO");
        doubles.add("INLOW");
        doubles.add("INSCOE");
        doubles.add("JACQUOT");
        doubles.add("JANDREAU");
        doubles.add("JARREAU");
        doubles.add("KAYO");
        doubles.add("KOWTOW");
        doubles.add("LABEAU");
        doubles.add("LAFOE");
        doubles.add("LAMBEAU");
        doubles.add("LAMBREAU");
        doubles.add("LAREAU");
        doubles.add("LAVEAU");
        doubles.add("LEBEAU");
        doubles.add("LEBOW");
        doubles.add("LEBOWE");
        doubles.add("LEDLOW");
        doubles.add("LEGAULT");
        doubles.add("LELEUX");
        doubles.add("LETTAU");
        doubles.add("LHEUREUX");
        doubles.add("LIENAU");
        doubles.add("LOEWE");
        doubles.add("LOZEAU");
        doubles.add("MALVEAUX");
        doubles.add("MANSEAU");
        doubles.add("MARCEAU");
        doubles.add("MARCEAUX");
        doubles.add("MARGAUX");
        doubles.add("MAYEUX");
        doubles.add("MICHAUD");
        doubles.add("MICHAUX");
        doubles.add("MICHEAUX");
        doubles.add("MIGNEAULT");
        doubles.add("MINEAU");
        doubles.add("MONCEAUX");
        doubles.add("MONGEAU");
        doubles.add("MONROE");
        doubles.add("MOREAU");
        doubles.add("MORNEAU");
        doubles.add("MORNEAULT");
        doubles.add("MOUSSEAU");
        doubles.add("MUNRO");
        doubles.add("NADEAU");
        doubles.add("NEDEAU");
        doubles.add("NEVEAU");
        doubles.add("NOUVEAU");
        doubles.add("OUTGROW");
        doubles.add("PAPO");
        doubles.add("PERNOD");
        doubles.add("PEROT");
        doubles.add("PERREAULT");
        doubles.add("PEUGEOT");
        doubles.add("PINEAU");
        doubles.add("PLATEAU");
        doubles.add("PRIMEAU");
        doubles.add("PRIMEAUX");
        doubles.add("PRUNEAU");
        doubles.add("RAMBEAU");
        doubles.add("RENAUD");
        doubles.add("RENAULT");
        doubles.add("RENEAU");
        doubles.add("RIDEAU");
        doubles.add("RIDEAUX");
        doubles.add("RIENDEAU");
        doubles.add("RONDEAU");
        doubles.add("ROUGEAU");
        doubles.add("ROULEAU");
        doubles.add("ROUSSEAU");
        doubles.add("SOCO");
        doubles.add("SOILEAU");
        doubles.add("TABLEAU");
        doubles.add("TABLEAUX");
        doubles.add("TAROT");
        doubles.add("TEBEAU");
        doubles.add("TETREAULT");
        doubles.add("THEBEAU");
        doubles.add("THIBAULT");
        doubles.add("THIBEAU");
        doubles.add("THIBEAUX");
        doubles.add("THIEBAUD");
        doubles.add("THOREAU");
        doubles.add("THURNAU");
        doubles.add("TONDREAU");
        doubles.add("TRUDEAU");
        doubles.add("TRUFFAUT");
        doubles.add("TURBOT");
        doubles.add("UNGO");
        doubles.add("UNO");
        doubles.add("VALLEAU");
        doubles.add("VEILLEUX");
        doubles.add("VIAU");
        doubles.add("VIEAU");
        doubles.add("VIENNEAU");
        doubles.add("VIGNEAU");
        doubles.add("VIGNEAULT");
        
        triples.add("APROPOS");
        triples.add("PINSONEAULT");
        triples.add("TAEKWONDO");
        triples.add("TALLYHO");
        triples.add("THERIAULT");
        triples.add("THERRIAULT");
        triples.add("TOURTELOT");
        triples.add("UNDERGO");
        triples.add("OVERFLOW");
        triples.add("KOWTOW");
        triples.add("PLOUGH");

    }

    public ArrayList<String> getSingleSyllables() {
        return singles;
    }

    public ArrayList<String> getDoubleSyllables() {
        return doubles;
    }

    public ArrayList<String> getTripleSyllables() {
        return triples;
    }

    public ArrayList<String> getQuadrupleSyllables() {
        return quadruples;
    }

    public ArrayList<String> getQuintupleSyllables() {
        return quintuples;
    }

    public ArrayList<String> getSextupleSyllables() {
        return sextuples;
    }
}
