package com.mikemilla.wordnerd.words;

import com.mikemilla.wordnerd.Syllables;

import java.util.ArrayList;

public class Ray implements Syllables {

    public static ArrayList<String> singles = new ArrayList<String>();
    public static ArrayList<String> doubles = new ArrayList<String>();
    public static ArrayList<String> triples = new ArrayList<String>();
    public static ArrayList<String> quadruples = new ArrayList<String>();
    public static ArrayList<String> quintuples = new ArrayList<String>();
    public static ArrayList<String> sextuples = new ArrayList<String>();

    public Ray() {
        singles.add("AE");
        singles.add("AY");
        singles.add("BAY");
        singles.add("BEY");
        singles.add("BLAY");
        singles.add("BLEY");
        singles.add("BRAE");
        singles.add("BRAY");
        singles.add("BREY");
        singles.add("CACHE");
        singles.add("CARRE");
        singles.add("CAY");
        singles.add("CHE");
        singles.add("CLAY");
        singles.add("CRAY");
        singles.add("DAE");
        singles.add("DAY");
        singles.add("DEY");
        singles.add("DRAY");
        singles.add("DREY");
        singles.add("FAY");
        singles.add("FEY");
        singles.add("FLAY");
        singles.add("FRAY");
        singles.add("FREY");
        singles.add("GAI");
        singles.add("GALLE");
        singles.add("GAY");
        singles.add("GRAY");
        singles.add("GREY");
        singles.add("GUAY");
        singles.add("GWAY");
        singles.add("HAIGH");
        singles.add("HAY");
        singles.add("HEY");
        singles.add("HWE");
        singles.add("JAE");
        singles.add("JAY");
        singles.add("JAYE");
        singles.add("KAY");
        singles.add("KLAY");
        singles.add("KLEY");
        singles.add("KRAY");
        singles.add("KREY");
        singles.add("LAIT");
        singles.add("LAY");
        singles.add("LEI");
        singles.add("LEY");
        singles.add("MAE");
        singles.add("MAY");
        singles.add("MEY");
        singles.add("NAY");
        singles.add("NEIGH");
        singles.add("NEJ");
        singles.add("NEY");
        singles.add("PAY");
        singles.add("PEI");
        singles.add("PLAY");
        singles.add("PRAY");
        singles.add("PREY");
        singles.add("QUAYE");
        singles.add("RAE");
        singles.add("REA");
        singles.add("REY");
        singles.add("SAY");
        singles.add("SAYE");
        singles.add("SCHEY");
        singles.add("SCHLEY");
        singles.add("SEAY");
        singles.add("SHAY");
        singles.add("SHEA");
        singles.add("SLAY");
        singles.add("SLEIGH");
        singles.add("SMAY");
        singles.add("SNAY");
        singles.add("SPEY");
        singles.add("SPLAY");
        singles.add("SPRAY");
        singles.add("STAY");
        singles.add("STRAY");
        singles.add("STREY");
        singles.add("SWAY");
        singles.add("TAE");
        singles.add("TAY");
        singles.add("THEY");
        singles.add("TORME");
        singles.add("TRAY");
        singles.add("TRE");
        singles.add("VEY");
        singles.add("WAY");
        singles.add("WEI");
        singles.add("WEIGH");
        singles.add("WEY");
        singles.add("WHEY");
        singles.add("WRAY");
        singles.add("YAY");
        singles.add("YEA");
        
        doubles.add("ADAY");
        doubles.add("AGGREY");
        doubles.add("AIGNER");
        doubles.add("ALLAIS");
        doubles.add("ALLAY");
        doubles.add("ANWAY");
        doubles.add("ARRAY");
        doubles.add("ASAY");
        doubles.add("ASTRAY");
        doubles.add("AWAY");
        doubles.add("BALLET");
        doubles.add("BANPAIS");
        doubles.add("BEAUPRE");
        doubles.add("BEAUVAIS");
        doubles.add("BENET");
        doubles.add("BERNAY");
        doubles.add("BETRAY");
        doubles.add("BOMBAY");
        doubles.add("BOULAIS");
        doubles.add("BOULAY");
        doubles.add("BOUQUET");
        doubles.add("BOUYGUES");
        doubles.add("BUFFET");
        doubles.add("CAFE");
        doubles.add("CALAIS");
        doubles.add("CALLAIS");
        doubles.add("CALVEY");
        doubles.add("CATHAY");
        doubles.add("CHALET");
        doubles.add("CISKEI");
        doubles.add("CLICHE");
        doubles.add("CODAY");
        doubles.add("CONVEY");
        doubles.add("CROCHET");
        doubles.add("CROQUET");
        doubles.add("DECAY");
        doubles.add("DEFRAY");
        doubles.add("DEKAY");
        doubles.add("DELAY");
        doubles.add("DELRAY");
        doubles.add("DEVEY");
        doubles.add("DISMAY");
        doubles.add("DISPLAY");
        doubles.add("DONAIS");
        doubles.add("DORAIS");
        doubles.add("DOSSIER");
        doubles.add("DOVEY");
        doubles.add("DUMAIS");
        doubles.add("DUPAY");
        doubles.add("ESSAY");
        doubles.add("FABERGE");
        doubles.add("FILET");
        doubles.add("FILLET");
        doubles.add("FRANCAIS");
        doubles.add("GERAIS");
        doubles.add("GERVAIS");
        doubles.add("HALFWAY");
        doubles.add("HEFEI");
        doubles.add("HERVEY");
        doubles.add("HEVEY");
        doubles.add("HONGWEI");
        doubles.add("HOORAY");
        doubles.add("HURRAY");
        doubles.add("ILHAE");
        doubles.add("IMLAY");
        doubles.add("JACQUET");
        doubles.add("JAQUAY");
        doubles.add("JOSE");
        doubles.add("JOURET");
        doubles.add("KAMEI");
        doubles.add("LANGLAIS");
        doubles.add("LEVEY");
        doubles.add("LIHUE");
        doubles.add("LURVEY");
        doubles.add("MACKAY");
        doubles.add("MACKNAY");
        doubles.add("MACLAY");
        doubles.add("MACRAE");
        doubles.add("MALTAIS");
        doubles.add("MANET");
        doubles.add("MARAIS");
        doubles.add("MARQUAI");
        doubles.add("MCBAY");
        doubles.add("MCCAY");
        doubles.add("MCCLAY");
        doubles.add("MCCRAE");
        doubles.add("MCCRAY");
        doubles.add("MCCREA");
        doubles.add("MCGRAY");
        doubles.add("MCKAY");
        doubles.add("MCLAY");
        doubles.add("MCNAY");
        doubles.add("MCQUAY");
        doubles.add("MCRAE");
        doubles.add("MCRAY");
        doubles.add("MCSHEA");
        doubles.add("MCSTAY");
        doubles.add("MCVAY");
        doubles.add("MCVEIGH");
        doubles.add("MCVEY");
        doubles.add("MILLAY");
        doubles.add("MOBAY");
        doubles.add("MONET");
        doubles.add("MORAIS");
        doubles.add("MORAY");
        doubles.add("MOUTRAY");
        doubles.add("MULVEY");
        doubles.add("NIHEI");
        doubles.add("NIKKEI");
        doubles.add("NISEI");
        doubles.add("NISSEI");
        doubles.add("OBEY");
        doubles.add("ODAY");
        doubles.add("OK");
        doubles.add("OLAY");
        doubles.add("ORSAY");
        doubles.add("OSHEA");
        doubles.add("PALAIS");
        doubles.add("PARFAIT");
        doubles.add("PARQUET");
        doubles.add("PASSE");
        doubles.add("PEVEY");
        doubles.add("PORCHER");
        doubles.add("PORTRAY");
        doubles.add("PREPAY");
        doubles.add("PUREE");
        doubles.add("PURVEY");
        doubles.add("RENE");
        doubles.add("RENEE");
        doubles.add("REPAY");
        doubles.add("REPLAY");
        doubles.add("RESNAIS");
        doubles.add("RISQUE");
        doubles.add("ROGET");
        doubles.add("SACHET");
        doubles.add("SAUTE");
        doubles.add("SERGEI");
        doubles.add("SERVAIS");
        doubles.add("SEVEY");
        doubles.add("SHINSEI");
        doubles.add("SINAY");
        doubles.add("SOCHET");
        doubles.add("SOIREE");
        doubles.add("SORBET");
        doubles.add("SOUFFLE");
        doubles.add("STUPAY");
        doubles.add("SURVEY");
        doubles.add("TODAY");
        doubles.add("TORAY");
        doubles.add("TOUPEE");
        doubles.add("TURVEY");
        doubles.add("VADNAIS");
        doubles.add("VALET");
        doubles.add("VOISEY");
        doubles.add("ZALAY");
        
        triples.add("ANTIGAY");
        triples.add("ATTACHE");
        triples.add("BEYONCE");
        triples.add("BOUVIER");
        triples.add("CABARET");
        triples.add("CABERNET");
        triples.add("CHEVROLET");
        triples.add("DESERET");
        triples.add("DISARRAY");
        triples.add("DISOBEY");
        triples.add("DUNLAVEY");
        triples.add("EVERYDAY");
        triples.add("FARAWAY");
        triples.add("FIANCE");
        triples.add("FILEAWAY");
        triples.add("JONBENET");
        triples.add("LIBERTE");
        triples.add("MCGARVEY");
        triples.add("MESERVEY");
        triples.add("MONTEREY");
        triples.add("MONTERREY");
        triples.add("OVERPLAY");
        triples.add("OVERSTAY");
        triples.add("PERRIER");
        triples.add("PIAGET");
        triples.add("PINOCHET");
        triples.add("REDISPLAY");
        triples.add("TOUVIER");
        triples.add("UNDERPAY");
        triples.add("UNDERPLAY");
        triples.add("UNDERWAY");
        triples.add("CABRIOLET");
        triples.add("COMMUNIQUE");
        triples.add("NAIVETE");
        triples.add("SOCIETE");
        triples.add("YAKUTAKAY");
        
        doubles.add("CACHE");
        doubles.add("BENET");
        doubles.add("BUFFET");
        doubles.add("CHALET");
        
        triples.add("FIANCE");
        triples.add("PERRIER");
    }

    public ArrayList<String> getSingleSyllables() {
        return singles;
    }

    public ArrayList<String> getDoubleSyllables() {
        return doubles;
    }

    public ArrayList<String> getTripleSyllables() {
        return triples;
    }

    public ArrayList<String> getQuadrupleSyllables() {
        return quadruples;
    }

    public ArrayList<String> getQuintupleSyllables() {
        return quintuples;
    }

    public ArrayList<String> getSextupleSyllables() {
        return sextuples;
    }
}
